### ISSUE TITLE
An unexpected error occurred invoking 'QueryTableDesign'

### ISSUE THREAD

**Issue by waldo1001** [dynasist/ALStudio#1]
When openen a Page Designer:

````
[AL Studio][2020-10-08T20:15:32.969Z][Debug]: fail: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[8]
      Failed to invoke hub method 'QueryPageDesign'.
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at ALObjectParser.Library.ALTable.<>c.<ProcessSections>b__21_0(IALSection s)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
   at System.Linq.Enumerable.SelectIPartitionIterator`2.ToList()
   at ALStudio.Server.Services.ALObjectService.UpdatePageFields(ALPage page)
   at ALStudio.Server.Services.ALObjectService.GetPageDesign(SymbolData info, Boolean skipSourceTable)
   at ALStudio.Server.ALStudioHub.QueryPageDesign(SymbolData info)
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.ExecuteHubMethod(ObjectMethodExecutor methodExecutor, THub hub, Object[] arguments)
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.<>c__DisplayClass13_0.<<Invoke>g__ExecuteInvocation|0>d.MoveNext()


```



```
[AL Studio][2020-10-08T20:17:06.982Z][Debug]: fail: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[8]
      Failed to invoke hub method 'QueryPageDesign'.
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at ALObjectParser.Library.ALTable.<>c.<ProcessSections>b__21_0(IALSection s)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
   at System.Linq.Enumerable.SelectIPartitionIterator`2.ToList()
   at ALStudio.Server.Services.ALObjectService.UpdatePageFields(ALPage page)
   at ALStudio.Server.Services.ALObjectService.GetPageDesign(SymbolData info, Boolean skipSourceTable)
   at ALStudio.Server.ALStudioHub.QueryPageDesign(SymbolData info)
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.ExecuteHubMethod(ObjectMethodExecutor methodExecutor, THub hub, Object[] arguments)
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.<>c__DisplayClass13_0.<<Invoke>g__ExecuteInvocation|0>d.MoveNext()
```

**Comment by martonsagi** [comment]
Hi @waldo1001 

This is probably due to file parsing but I can't reproduce this issue. Do you get this for all kinds of pages or just specific ones?
I'd need some pointer to move on.

Thanks!

**Comment by martonsagi** [comment]
Cancelling the first discovery might have also caused this (low probability). Anyway, the notification is not cancellable anymore as it is a mandatory first step to gather data.
