### ISSUE TITLE
An unexpected error occured invoking "querytranslations"

### ISSUE THREAD

**Issue by waldo1001** [dynasist/ALStudio#15]
When clicking translations:
![image](https://user-images.githubusercontent.com/12088142/100774923-e7e42680-3402-11eb-9283-8fc48d57282e.png)

it's a multiroot workspace.

```

[AL Studio][2020-12-01T17:28:31.169Z][Debug]: fail: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[8]
      Failed to invoke hub method 'QueryTranslations'.
      System.AggregateException: One or more errors occurred. (There is an error in XML document (8, 12).)
       ---> System.InvalidOperationException: There is an error in XML document (8, 12).
       ---> System.Xml.XmlException: There are multiple root elements. Line 8, position 12.
         at System.Xml.XmlTextReaderImpl.Throw(Exception e)
         at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
         at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
         at System.Xml.XmlReader.ReadEndElement()
         at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderxliff.Read7_xliff(Boolean isNullable, Boolean checkType)
         at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderxliff.Read8_xliff()
         --- End of inner exception stack trace ---
         at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
         at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
         at ALStudio.Server.Services.TranslationService.<>c.<GetTranslationModel>b__10_11(String xlfPath)
         at System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
         at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
         at System.Linq.Parallel.SpoolingTaskBase.Work()
         at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location ---
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
         --- End of inner exception stack trace ---
         at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
         at System.Linq.Parallel.SpoolingTask.SpoolStopAndGo[TInputOutput,TIgnoreKey](QueryTaskGroupState groupState, PartitionedStream`2 partitions, SynchronousChannel`1[] channels, TaskScheduler taskScheduler)
         at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
         at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
         at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
         at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
         at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
         at System.Linq.Parallel.QueryOpeningEnumerator`1.OpenQuery()
         at System.Linq.Parallel.QueryOpeningEnumerator`1.MoveNext()
         at System.Linq.ParallelEnumerable.ToList[TSource](ParallelQuery
[AL Studio][2020-12-01T17:28:31.169Z][Debug]: `1 source)
         at ALStudio.Server.Services.TranslationService.GetTranslationModel(IEnumerable`1 paths)
         at ALObjectDesigner.Library.ALObjectCollectorCacheService.GetTranslation(Boolean reload)
         at ALStudio.Server.ALStudioHub.QueryTranslations(IEnumerable`1 paths)
         at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.ExecuteMethod(ObjectMethodExecutor methodExecutor, Hub hub, Object[] arguments)
         at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.<>c__DisplayClass16_0.<<Invoke>g__ExecuteInvocation|0>d.MoveNext()
```

**Comment by martonsagi** [comment]
How many translation files do you have? Do you edit them directly as text or with some external service?
Is it a BC17.x workspace?
Can you try it with the BC16.x version of it?

Thanks,
Marton

**Comment by waldo1001** [comment]
I can't try with v16, sorry.

We have 2 translations files per app, + a g.xlf .. . for 35 apps.  That makes 70 translations files + 35 generated xlfs.. .

**Comment by martonsagi** [comment]
Thanks, I'll create a similar workspace and try to repro this error.

**Comment by martonsagi** [comment]
Latest published build contains possible fixes for this error. Can you re-check it?

**Comment by martonsagi** [comment]
It has been resolved according to Twitter feedback. Thanks! :)
