### ISSUE TITLE
Cannot open "Fields" from AL Home

### ISSUE THREAD

**Issue by NKarolak** [dynasist/ALStudio#16]
When I try to open "Fields" from the AL Home:
![image](https://user-images.githubusercontent.com/34504100/100841661-e0ab3000-3477-11eb-91ee-10f41101bc2a.png)

Then I receive:

> An unexpected error occurred invoking 'GetTableFields' on the server. FormatException: Input string was not in a correct format.

Output:
```
[AL Studio][2020-12-02T07:23:44.554Z][Debug]: fail: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[8]
      Failed to invoke hub method 'GetTableFields'.
      System.FormatException: Input string was not in a correct format.
         at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
         at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
         at System.Int32.Parse(String s)
         at ALObjectParser.Library.ALTable.<>c.<ProcessSections>b__22_0(IALSection s)
         at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
         at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
         at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
         at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
         at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
         at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
         at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
         at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
         at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
         at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
         at ALStudio.Server.Services.ALObjectService.GetTableFields()
         at ALStudio.Server.Services.ALObjectService.GetTableFieldsModel(Boolean reload)
         at ALStudio.Server.ALStudioHub.GetTableFields()
         at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.ExecuteMethod(ObjectMethodExecutor methodExecutor, Hub hub, Object[] arguments)
         at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.<>c__DisplayClass16_0.<<Invoke>g__ExecuteInvocation|0>d.MoveNext()
```

**Comment by NKarolak** [comment]
Solved in upcoming version 0.9.664, thanks :-)
