### ISSUE TITLE
Backend connection lost

### ISSUE THREAD

**Issue by NKarolak** [dynasist/ALStudio#5]
I have opened a 17.1 Base Application repository, did not wait until everything was loaded but opened an object instead, when suddenly the following messages appeared in an **endless (?) loop**:
![image](https://user-images.githubusercontent.com/34504100/95992670-7dfdc680-0e2e-11eb-832a-319b25cbb193.png)
(please also note the highlighted typo).

Unfortunately I cannot provide any real repro scenario; but just in case you have an idea where to look at, or if me or anyone else can add a repro ...

**Comment by martonsagi** [comment]
I have experienced this today as well. Can you take look at the "Output / AL Studio" windows? Do you see any .NET Exceptions perhaps?
Investigation is underway. :)

Thanks!

**Comment by NKarolak** [comment]
I needed to close VS Code right after, since it looked like an endless loop, hence I am not sure whether the following logs are really related, but the time stamp looks plausible:

```
[AL Studio][2020-10-14T13:02:02.072Z][Debug]: info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 POST http://localhost:30001/alstudio/negotiate?negotiateVersion=1  0
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint '/alstudio/negotiate'
dbug: Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager[1]
      New connection 0DfMQM8xfdjADUP74xQlXQ created.
dbug: Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher[10]
      Sending negotiation response.
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint '/alstudio/negotiate'

[AL Studio][2020-10-14T13:02:02.096Z][Debug]: info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 100.0044ms 200 application/json

[AL Studio][2020-10-14T13:02:02.103Z][Debug]: info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:30001/alstudio?id=u7mVmIoOtSTW7jfyYPw53g  

[AL Studio][2020-10-14T13:02:02.107Z][Debug]: info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint '/alstudio'

[AL Studio][2020-10-14T13:02:02.526Z][Debug]: dbug: Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher[4]
      Establishing new connection.
dbug: Microsoft.AspNetCore.SignalR.HubConnectionHandler[5]
      OnConnectedAsync started.
dbug: Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport[1]
      Socket opened using Sub-Protocol: '(null)'.

[AL Studio][2020-10-14T13:02:02.555Z][Debug]: dbug: Microsoft.AspNetCore.SignalR.Internal.DefaultHubProtocolResolver[2]
      Found protocol implementation for requested protocol: json.

[AL Studio][2020-10-14T13:02:02.562Z][Debug]: dbug: Microsoft.AspNetCore.SignalR.HubConnectionContext[1]
      Completed connection handshake. Using HubProtocol 'json'.

[AL Studio][2020-10-14T13:02:03.352Z][Debug]: dbug: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[1]
      Received hub invocation: InvocationMessage { InvocationId: "0", Target: "HasValidLicense", Arguments: [  ], StreamIds: [  ] }.

[AL Studio][2020-10-14T13:02:03.655Z][Debug]: dbug: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[1]
      Received hub invocation: InvocationMessage { InvocationId: "1", Target: "QueryObjects", Arguments: [ System.Collections.Generic.List`1[System.String],  ], StreamIds: [  ] }.

[AL Studio][2020-10-14T13:02:06.308Z][Debug]: fail: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[8]
      Failed to invoke hub method 'QueryObjects'.
System.AggregateException: One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (Destination array was not long enough. Check the destination index, length, and the array's lower bounds. (Parameter 'destinationArray'))) (Destination array was not long enough. Check the destination index, length, and the array's lower bounds. (Parameter 'destinationArray')))) (Destination array was not long enough. Check the destination index, length, and the array's lower bounds. (Parameter 'destinationArray'))
 ---> System.ArgumentException: Destination array was not long enough. Check the destination index, length, and the array's lower bounds. (Parameter 'destinationArray')
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Collections.Generic.List`1.set_Capacity(Int32 value)
   at System.Collections.Generic.List`1.EnsureCapacity(Int32 min)
   at System.Collections.Generic.List`1.AddWithResize(T item)
   at ALObjectParser.Library.ALObjectReaderNew.OnGetObjectProperty(String Line, IALSection Target, String pattern)
   at ALObjectParser.Library.ALObjectReaderNew.<>c__DisplayClass21_0.<GetSectionProperties>b__2(String result)
   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
   at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.RunTaskSynchronously(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.OrderPreservingSpoolingTask`2.Spool(QueryTaskGroupState groupState, PartitionedStream`2 partitions, Shared`1 results, TaskScheduler taskScheduler)
   at System.Linq.Parallel.OrderPreservingMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.SortQueryOperatorResults`2.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 childPartitionedStream)
   at System.Linq.Parallel.WhereQueryOperator`1.WrapPartitionedStream[TKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, Boolean preferStriping, QuerySettings settings)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.SelectManyQueryOperator`3.WrapPartitionedStreamNotIndexed[TLeftKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, QuerySettings settings)
   at System.Linq.Parallel.SelectManyQueryOperator`3.WrapPartitionedStream[TLeftKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, Boolean preferStriping, QuerySettings settings)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.WhereQueryOperator`1.WrapPartitionedStream[TKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, Boolean preferStriping, QuerySettings settings)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.SortQueryOperatorResults`2.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
   at System.Linq.Parallel.QueryOpeningEnumerator`1.OpenQuery()
   at System.Linq.Parallel.QueryOpeningEnumerator`1.MoveNext()
   at System.Linq.ParallelEnumerable.ToList[TSource](ParallelQuery`1 source)
   at ALObjectDesigner.Library.ALObjectCollector.DiscoverLocalFiles(List`1 wkspcePaths, Boolean asFilePaths)
   at ALObjectDesigner.Library.ALObjectCollector.GetCollectorItems(List`1 wkspcePaths, Boolean localFiles)
   at ALObjectDesigner.Library.ALObjectCollector.Discover(List`1 wkspcePaths)
   at ALObjectDesigner.Library.ALObjectCollectorCacheService.LoadObjects()
   at ALObjectDesigner.Library.ALObjectCollectorCacheService.GetObjects(Boolean reload)
   at ALStudio.Server.ALStudioHub.QueryObjects(IEnumerable`1 paths, Nullable`1 reload)
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.ExecuteHubMethod(ObjectMethodExecutor methodExecutor, THub hub, Object[] arguments)
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.<>c__DisplayClass13_0.<<Invoke>g__ExecuteInvocation|0>d.MoveNext()

[AL Studio][2020-10-14T13:02:10.820Z][Debug]: dbug
[AL Studio][2020-10-14T13:02:10.820Z][Debug]: : Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[1]
      Received hub invocation: InvocationMessage { InvocationId: "2", Target: "QueryProjects", Arguments: [ System.Collections.Generic.List`1[System.String] ], StreamIds: [  ] }.

[AL Studio][2020-10-14T13:02:12.069Z][Debug]: dbug: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[1]
      Received hub invocation: InvocationMessage { InvocationId: "3", Target: "QueryDashboard", Arguments: [  ], StreamIds: [  ] }.

[AL Studio][2020-10-14T13:02:38.291Z][Debug]: Total time: 26,2077713

[AL Studio][2020-10-14T13:02:46.710Z][Debug]: dbug: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[1]
      Received hub invocation: InvocationMessage { InvocationId: "4", Target: "QueryDashboard", Arguments: [  ], StreamIds: [  ] }.

[AL Studio][2020-10-14T13:02:48.739Z][Debug]: dbug: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[1]
      Received hub invocation: InvocationMessage { InvocationId: "5", Target: "QueryDashboard", Arguments: [  ], StreamIds: [  ] }.

[AL Studio][2020-10-14T13:05:49.212Z][Debug]: dbug: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[1]
      Received hub invocation: InvocationMessage { InvocationId: "6", Target: "QueryDashboard", Arguments: [  ], StreamIds: [  ] }.

[AL Studio][2020-10-14T13:05:58.465Z][Debug]: dbug
[AL Studio][2020-10-14T13:05:58.465Z][Debug]: : Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[1]
      Received hub invocation: InvocationMessage { InvocationId: "7", Target: "QueryDashboard", Arguments: [  ], StreamIds: [  ] }.

[AL Studio][2020-10-14T13:08:28.191Z][Debug]: dbug: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[1]
      Received hub invocation: InvocationMessage { InvocationId: "8", Target: "QueryDashboard", Arguments: [  ], StreamIds: [  ] }.

[AL Studio][2020-10-14T13:08:33.525Z][Debug]: dbug: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[1]
      Received hub invocation: InvocationMessage { InvocationId: "9", Target: "QueryDashboard", Arguments: [  ], StreamIds: [  ] }.
```

**Comment by martonsagi** [comment]
It is helpful, thank you.

**Comment by martonsagi** [comment]
On a side note: Window Reload (CTRL+R) command is also sufficient to escape from such situation, you don't have to actually close VSCode.

**Comment by martonsagi** [comment]
@NKarolak do you have the following extensions activated?
* AL XML Documentation
* Waldo's CRS Extension

**Comment by martonsagi** [comment]
I have uploaded a new custom build with fixes, please check it: [https://github.com/dynasist/ALStudio/blob/master/builds/al-studio-0.9.999-issue5.vsix](https://github.com/dynasist/ALStudio/blob/master/builds/al-studio-0.9.999-issue5.vsix)
(It should also be a bit faster thanks to .NET 5 :)

**Comment by NKarolak** [comment]
I am using only Waldo's extension from your list.
Thanks, but I cannot install your VSIX: 

> Corrupt ZIP: end of central directory record signature not found

**Comment by martonsagi** [comment]
Strange. I just downloaded and installed it from the link, it worked. Can you download it again? Perhaps it was really a network issue for the first download. Alternatively, I sent you a OneDrive link on Twitter.

**Comment by NKarolak** [comment]
Thanks, the installation from OneDrive was successful. Please give me some time to observe the changes (currently I am not developing).

**Comment by NKarolak** [comment]
Still using the "issue5" version, the issue occurred again.
This time, I was on a Base Application 17.0 repository, SalesOrder.Page.al, and I searched for action names using the search function, probably before the AL Studio was completely loaded.

The following error was looped:

```
[AL   Studio][2020-10-16T11:44:36.013Z][Debug]: fail:   Microsoft.AspNetCore.SignalR.HubConnectionContext[6]
--
Failed writing message. Aborting connection.
System.NullReferenceException: Object reference not set to an instance   of an object.
at   ALObjectDesigner.Library.ALObjectCollector.<>c__DisplayClass19_2.<Discover>b__2(ALPropertyCollectionItem   f)
at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source,   Func`2 predicate, Boolean& found)
at   ALObjectDesigner.Library.ALObjectCollector.<>c__DisplayClass19_0.<Discover>b__1(ALProperty   x)
at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
at   System.Text.Json.Serialization.Converters.IEnumerableOfTConverter`2.OnWriteResume(Utf8JsonWriter   writer, TCollection value, JsonSerializerOptions options, WriteStack&   state)
at   System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnTryWrite(Utf8JsonWriter   writer, TCollection value, JsonSerializerOptions options, WriteStack&   state)
at   System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter   writer, T& value, JsonSerializerOptions options, WriteStack& state)
at System.Text.Json.JsonPropertyInfo`1.GetMemberAndWriteJson(Object   obj, WriteStack& state, Utf8JsonWriter writer)
at   System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter   writer, T value, JsonSerializerOptions options, WriteStack& state)
at   System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter   writer, T& value, JsonSerializerOptions options, WriteStack& state)
at   System.Text.Json.Serialization.Converters.ListOfTConverter`2.OnWriteResume(Utf8JsonWriter   writer, TCollection value, JsonSerializerOptions options, WriteStack&   state)
at   System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnTryWrite(Utf8JsonWriter   writer, TCollection value, JsonSerializerOptions options, WriteStack&   state)
at   System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter   writer, T& value, JsonSerializerOptions options, WriteStack& state)
at   System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter   writer, T& value, JsonSerializerOptions options, WriteStack& state)
at   System.Text.Json.Serialization.JsonConverter`1.WriteCoreAsObject(Utf8JsonWriter   writer, Object value, JsonSerializerOptions options, WriteStack& state)
at System.Text.Json.JsonSerializer.WriteCore[TValue](JsonConverter   jsonConverter, Utf8JsonWriter writer, TValue& value,   JsonSerializerOptions options, WriteStack& state)
at System.Text.Json.JsonSerializer.WriteCore[TValue](Utf8JsonWriter   writer, TValue& value, Type inputType, JsonSerializerOptions options)
at System.Text.Json.JsonSerializer.Serialize(Utf8JsonWriter writer,   Object value, Type inputType, JsonSerializerOptions options)
at   Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteArguments(Object[]   arguments, Utf8JsonWriter writer)
at   Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteInvocationMessage(InvocationMessage   message, Utf8JsonWriter writer)
at   Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteMessageCore(HubMessage   message, IBufferWriter`1 stream)
at   Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteMessage(HubMessage   message, IBufferWriter`1 output)
at   Microsoft.AspNetCore.SignalR.Protocol.HubProtocolExtensions.GetMessageBytes(IHubProtocol   hubProtocol, HubMessage message)
at   Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.GetMessageBytes(HubMessage   message)
at   Microsoft.AspNetCore.SignalR.SerializedHubMessage.GetSerializedMessage(IHubProtocol   protocol)
at   Microsoft.AspNetCore.SignalR.HubConnectionContext.WriteCore(SerializedHubMessage   message, CancellationToken cancellationToken)
```

Scrolling up the log, the first error was
See `****** NEW LINE *******`

```
[AL   Studio][2020-10-16T11:43:04.267Z][Debug]: fail:   Microsoft.AspNetCore.SignalR.HubConnectionContext[6]
--
Failed writing message. Aborting connection.
System.NullReferenceException: Object reference not set to an instance   of an object.
at   ALObjectDesigner.Library.ALObjectCollector.<>c__DisplayClass19_2.<Discover>b__2(ALPropertyCollectionItem   f)
at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source,   Func`2 predicate, Boolean& found)
// ****** NEW LINE ******* at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1   source, Func`2 predicate) 
at   ALObjectDesigner.Library.ALObjectCollector.<>c__DisplayClass19_0.<Discover>b__1(ALProperty   x)
at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
at   System.Text.Json.Serialization.Converters.IEnumerableOfTConverter`2.OnWriteResume(Utf8JsonWriter   writer, TCollection value, JsonSerializerOptions options, WriteStack&   state)
at   System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnTryWrite(Utf8JsonWriter   writer, TCollection value, JsonSerializerOptions options, WriteStack&   state)
at   System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter   writer, T& value, JsonSerializerOptions options, WriteStack& state)
at System.Text.Json.JsonPropertyInfo`1.GetMemberAndWriteJson(Object   obj, WriteStack& state, Utf8JsonWriter writer)
at   System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter   writer, T value, JsonSerializerOptions options, WriteStack& state)
at   System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter   writer, T& value, JsonSerializerOptions options, WriteStack& state)
at   System.Text.Json.Serialization.Converters.ListOfTConverter`2.OnWriteResume(Utf8JsonWriter   writer, TCollection value, JsonSerializerOptions options, WriteStack&   state)
at   System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnTryWrite(Utf8JsonWriter   writer, TCollection value, JsonSerializerOptions options, WriteStack&   state)
at   System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter   writer, T& value, JsonSerializerOptions options, WriteStack& state)
at   System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter   writer, T& value, JsonSerializerOptions options, WriteStack& state)
at   System.Text.Json.Serialization.JsonConverter`1.WriteCoreAsObject(Utf8JsonWriter   writer, Object value, JsonSerializerOptions options, WriteStack& state)
at System.Text.Json.JsonSerializer.WriteCore[TValue](JsonConverter   jsonConverter, Utf8JsonWriter writer, TValue& value,   JsonSerializerOptions options, WriteStack& state)
at System.Text.Json.JsonSerializer.WriteCore[TValue](Utf8JsonWriter   writer, TValue& value, Type inputType, JsonSerializerOptions options)
at System.Text.Json.JsonSerializer.Serialize[TValue](Utf8JsonWriter   writer, TValue& value, Type type, JsonSerializerOptions options)
at System.Text.Json.JsonSerializer.Serialize(Utf8JsonWriter writer,   Object value, Type inputType, JsonSerializerOptions options)
at   Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteArguments(Object[]   arguments, Utf8JsonWriter writer)
at   Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteInvocationMessage(InvocationMessage   message, Utf8JsonWriter writer)
at   Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteMessageCore(HubMessage   message, IBufferWriter`1 stream)
at   Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteMessage(HubMessage   message, IBufferWriter`1 output)
at   Microsoft.AspNetCore.SignalR.Protocol.HubProtocolExtensions.GetMessageBytes(IHubProtocol   hubProtocol, HubMessage message)
at   Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.GetMessageBytes(HubMessage   message)
at   Microsoft.AspNetCore.SignalR.SerializedHubMessage.GetSerializedMessage(IHubProtocol   protocol)
at   Microsoft.AspNetCore.SignalR.HubConnectionContext.WriteCore(SerializedHubMessage   message, CancellationToken cancellationToken)
```

**Comment by martonsagi** [comment]
I was not able to reproduce this, however I tried to search within a file during extension activation. Did you refer to the built-in VSCode search functions?

I will let you know when a new internal build is available with possible fixes, I want to fix this before publishing the next beta build.

**Comment by NKarolak** [comment]
> Did you refer to the built-in VSCode search functions?

Yes, Ctrl + F within the file.

**Comment by martonsagi** [comment]
@NKarolak I have published a new beta version on the Marketplace that contains all the previous fixes.
I leave this issue open until final confirmation and will publish hotfix build if the issue is still present.

**Comment by NKarolak** [comment]
OK, I am now using v0.9.564 and I would like to continue my observation, but ... AL Home does not load anymore, the page is empty, no error :-( 
I have repeated it with a complete uninstall and reinstall again, but no success. No errors logged.

```
[AL Studio][2020-10-19T12:54:10.161Z][Debug]: AL Studio Backend is up and running.

[AL Studio][2020-10-19T12:54:10.305Z][Debug]: info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 POST http://localhost:30000/alstudio/negotiate?negotiateVersion=1 - 0

[AL Studio][2020-10-19T12:54:10.360Z][Debug]: info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint '/alstudio/negotiate'

[AL Studio][2020-10-19T12:54:10.379Z][Debug]: dbug: Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager[1]
      New connection dj444aDQ1ephHZI7Wc3npg created.

[AL Studio][2020-10-19T12:54:10.404Z][Debug]: dbug: Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher[10]
      Sending negotiation response.

[AL Studio][2020-10-19T12:54:10.423Z][Debug]: info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint '/alstudio/negotiate'

[AL Studio][2020-10-19T12:54:10.429Z][Debug]: info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 POST http://localhost:30000/alstudio/negotiate?negotiateVersion=1 - 0 - 200 316 application/json 122.8479ms

[AL Studio][2020-10-19T12:54:10.433Z][Debug]: info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:30000/alstudio?id=9BU8MwB0oEfVPaL0gwIclg - -
info
[AL Studio][2020-10-19T12:54:10.433Z][Debug]: : Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint '/alstudio'

[AL Studio][2020-10-19T12:54:10.450Z][Debug]: dbug: Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher[4]
      Establishing new connection.

[AL Studio][2020-10-19T12:54:10.455Z][Debug]: dbug: Microsoft.AspNetCore.SignalR.HubConnectionHandler[5]
      OnConnectedAsync started.

[AL Studio][2020-10-19T12:54:10.464Z][Debug]: dbug: Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport[1]
      Socket opened using Sub-Protocol: '(null)'.

[AL Studio][2020-10-19T12:54:10.512Z][Debug]: dbug: Microsoft.AspNetCore.SignalR.Internal.DefaultHubProtocolResolver[2]
      Found protocol implementation for requested protocol: json.

[AL Studio][2020-10-19T12:54:10.515Z][Debug]: dbug: Microsoft.AspNetCore.SignalR.HubConnectionContext[1]
      Completed connection handshake. Using HubProtocol 'json'.

[AL Studio][2020-10-19T12:54:10.660Z][Debug]: dbug: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[1]
      Received hub invocation: InvocationMessage { InvocationId: "0", Target: "HasValidLicense", Arguments: [  ], StreamIds: [  ] }.

[AL Studio][2020-10-19T12:54:10.803Z][Debug]: dbug: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[1]
      Received hub invocation: InvocationMessage { InvocationId: "1", Target: "QueryObjects", Arguments: [ System.Collections.Generic.List`1[System.String],  ], StreamIds: [  ] }.

[AL Studio][2020-10-19T12:54:15.046Z][Debug]: Total time: 4,2399897

[AL Studio][2020-10-19T12:54:15.700Z][Debug]: dbug: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[1]
      Received hub invocation: InvocationMessage { InvocationId: "2", Target: "SetDirtyCache", Arguments: [ True ], StreamIds: [  ] }.
dbug: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[1]
      Received hub invocation: InvocationMessage { InvocationId: "3", Target: "QueryTranslations", Arguments: [ System.Collections.Generic.List`1[System.String] ], StreamIds: [  ] }.

[AL Studio][2020-10-19T12:54:15.704Z][Debug]: Translation processing started...

[AL Studio][2020-10-19T12:54:15.933Z][Debug]: Translation processing update... 0,2281202
Translation processing ended...0,2282417

[AL Studio][2020-10-19T12:54:23.748Z][Debug]: dbug
[AL Studio][2020-10-19T12:54:23.748Z][Debug]: : Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[1]
      Received hub invocation: InvocationMessage { InvocationId: "4", Target: "QueryProjects", Arguments: [ System.Collections.Generic.List`1[System.String] ], StreamIds: [  ] }.
```

**Comment by martonsagi** [comment]
I see it, yes. It's not related to this issue, the build process did not include a webapp dependency, which was working like 3-4 hours ago :(

I'm on it, please downgrade to the previous version until then.

**Comment by martonsagi** [comment]
Fixed, autopublish should be finished within 20-25 minutes.

**Comment by martonsagi** [comment]
@NKarolak : are you still experiencing this issue?

**Comment by NKarolak** [comment]
No I didn't, but on the other hand I didn't have much possibilities to observe.
Anyway, I'll close the issue, and if I encounter it again ... I'll know what to do ;-)
