### ISSUE TITLE
Go to definition on a standard object: "A request has failed"

### ISSUE THREAD

**Issue by NKarolak** [dynasist/ALStudio#6]
An error is thrown from the AL Language extension actually, but I can reproduce it only with AL Studio involved.
Can you confirm it is a mere AL Language error?

I am developing an extension depending on the Base Application.
1. In AL Home, go to table 36, and click on the name "Sales Header". 
2. In the Fields page, click on "Source".
3. Go to field 1, and try F12 on Enum "Sales Document Type".
4. Error: "A request has failed. See the output for more information."

Output AL:
```
[Error - 13:02:05] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/gotodefinition' failed with error: 'Index was outside the bounds of the array.'
Details:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.FilePathHelper.ParsePreviewFileUrl(Uri uri) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\FilePathHelper.cs:line 97
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.ReferenceSymbolDefinitionManager.GetDeclaringSymbolAsync(Uri previewUri, CancellationToken token) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\ReferenceSymbolDefinitionManager.cs:line 137
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.ReferenceSymbolDefinitionManager.GetContentAsync(Uri previewUri, LaunchConfiguration configuration, CancellationToken token, Boolean relyOnCachedValue) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\ReferenceSymbolDefinitionManager.cs:line 73
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.ReferenceSymbolDefinitionManager.GetDefinitionForSymbolAtPositionAsync(Uri previewUri, Position requestPosition, LaunchConfiguration configuration, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\ReferenceSymbolDefinitionManager.cs:line 101
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.AlDefinitionRequestHandler.ProcessRequestAsync(AlDefinitionRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\AlDefinitionRequestHandler.cs:line 50
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.NavServerRequestHandler`2.HandleAsync(T request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\NavServerRequestHandler.cs:line 40
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 65
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 80
```

If I disable AL Studio and open the `Sales Header.dal` (which btw does not include code, just the fields) and press F12 on the enum, it just says "No definition found for ...". But no unhandled error logged.

**Comment by martonsagi** [comment]
I have never been satisfied with the DAL thing, therefore I have created a custom document provider for loading source code from Symbol packages.
Unfortunately, AL Language extension does not support navigation within DAL/any other AL-like virtual files, hence the exception above. AL Studio's custom provider only amplifies this underlying issue.

There is a [Definition Provider](https://github.com/martonsagi/al-object-designer/blob/master/extension-al-object-designer/src/DalDefinitionProvider.ts) in AL Object Designer that I'm intending to port to AL Studio as well, see demo here:
https://twitter.com/sagimarton/status/1246219307689836545
This should resolve the exception.. at least I did not experience it while using AL Object Designer.

**Comment by martonsagi** [comment]
Good news: I was able to stop generating AL Language exceptions by applying some changes on my side.

So, it will work like this in the next beta (next week):
![ALStudio_DefinitionProvider](https://user-images.githubusercontent.com/18100709/96245926-34d18200-0fa8-11eb-95b8-37af6f4d5ec1.gif)

**Comment by NKarolak** [comment]
Cool, thanks!

**Comment by NKarolak** [comment]
Confirmed in preview version 0.9.559 - veeeery nice :-)

**Comment by martonsagi** [comment]
Thank you for the confirmation! If #5 also works, I'm ready to publish the new beta. :)

(You can try placing breakpoints, that should also work - although the red dot is not yet visible while debugging, but it stops at the breakpoints)
